version: '3.1'

name: "MongoDb-Example"

services:
  web:
    build: .
    ports:
        - "127.0.0.1:8080:80"
    depends_on:
        - mongodb
        - mongo-express

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
    depends_on:
      - mongodb